{{- if .Values.browserless.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "browserless.name" . }}
  labels:
    {{- include "browserless.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "browserless.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "browserless.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      containers:
        - name: {{ .Chart.Name }}-browserless
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.browserless.image.repository }}:{{ .Values.browserless.image.tag }}"
          imagePullPolicy: {{ .Values.browserless.image.pullPolicy }}
          ports:
            - name: browserless-ws
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - sh
                - "-c"
                - "curl --fail -q localhost:3000/pressure?token=${TOKEN}"
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - "-c"
                - "curl --fail -q localhost:3000/pressure?token=${TOKEN}"
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.browserless.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "browserless.name" . }}-configmap
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: BROWSERLESS_TOKEN
                  name: {{ include "print-browserless.name" . }}
{{- end }}
