apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "browserless.name" . }}-configmap
  labels:
    {{- include "browserless.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
data:
  CONCURRENT: {{ .Values.browserless.maxConcurrentSessions | quote }}
  TIMEOUT: {{ .Values.browserless.connectionTimeout | quote }}
  QUEUED: {{ .Values.browserless.maxQueueLength | quote }}
