{{ $secretName := include "print-browserless.name" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "print.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- include "gen.secret" (dict "namespace" .Release.Namespace "secretName" $secretName "key" "BROWSERLESS_TOKEN") | nindent 2 }}
